### ISSUE TITLE
画廊新版本那块应该是个list

### ISSUE THREAD

**Issue by duzhaokun123** [NekoInverter/EhViewer#10]
上次给的链接不好，用这个 https://e-hentai.org/g/1698191/416452a2b6/

**Comment by NekoInverter** [comment]
没时间（

**Comment by NekoInverter** [comment]
> 我周六弄，
> 
> 可以引入kotlin吗

Kotlin 不行（

**Comment by duzhaokun123** [comment]
行吧

**Comment by duzhaokun123** [comment]
由于不可抗拒的因素导致不能写了，抱歉

**Comment by NekoInverter** [comment]
[release.zip](https://github.com/NekoInverter/EhViewer/files/5415044/release.zip)
看看这个？

**Comment by NekoInverter** [comment]
![Screenshot_20201021-181107](https://user-images.githubusercontent.com/42698724/96706188-d6057180-13c8-11eb-8101-fb9ab4811771.png)
