### ISSUE TITLE
请问能否使用1.72版本的修改主题模式的位置呢

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [NekoInverter/EhViewer#11]
![t1](https://user-images.githubusercontent.com/48485664/92185573-e4361780-ee86-11ea-8e9e-f85133537a94.png)
![t2](https://user-images.githubusercontent.com/48485664/92185581-e7c99e80-ee86-11ea-95d0-3f9d56ba8a3e.png)
1.72版本可以通过在右滑菜单底部轻击2次修改主题模式。而1.78把修改深色模式的设置移动到了设置选项而非右滑菜单底部。似乎前者要便捷一些
如果采纳非常感谢!

**Comment by NekoInverter** [comment]
不是有吗

**Comment by StirrerCymbal5zn** [comment]
> 不是有吗

抱歉没说清楚><
月亮图标开关只可在暗色—亮色主题之间切换，纯黑深色主题需要在设置菜单栏设置。
如图，前2者是1.72的暗色主题
![1 72](https://user-images.githubusercontent.com/48485664/92197564-b233ae00-eea4-11ea-9b52-0aa283d7418a.jpg)
而后者是1.78的暗色主题
![1 78](https://user-images.githubusercontent.com/48485664/92197593-cd062280-eea4-11ea-9766-37ae7c6d64f2.jpg)

**Comment by NekoInverter** [comment]
我觉得动态切换暗色/黑色主题没什么用

**Comment by NekoInverter** [comment]
哦对了，切换以后从黑切主题变成深切主题是 Google 的 Bug
