### ISSUE TITLE
能问下怎么才能用中文标签么

### ISSUE THREAD

**Issue by jgq3035727** [NekoInverter/EhViewer#12]

**Comment by NekoInverter** [comment]
确保你能连上 raw.githubusercontent.com

**Comment by jgq3035727** [comment]
已经解决了，原来小米浏览器被拒接请求了，上个vpn就好了。谢谢

**Comment by jgq3035727** [comment]
更新之后卸载了一次，又没有中文标签了。连得上raw.githubusercontent.com网站之后呢？

**Comment by NekoInverter** [comment]
它会自动下载的

**Comment by NekoInverter** [comment]
https://github.com/NekoInverter/EhViewer/commit/e538b756e6e6b2ff15f30180dd220f613f56b665
现在不用梯子了

**Comment by k7kkl** [comment]
有提子才能下载翻译数据

**Comment by jgq3035727** [comment]
好的，非常感谢

**Comment by linktao159357** [comment]
使用梯子也无法下载

**Comment by yinzhefuyun** [comment]
1.7.15无法翻译标签，能否自行导入翻译标签？

**Comment by jgq3035727** [comment]
> 1.7.15无法翻译标签，能否自行导入翻译标签？

你1.7.14有翻译好的可以导出，然后在1.7.15导入就有翻译标签了。

**Comment by NekoInverter** [comment]
> 1.7.15无法翻译标签，能否自行导入翻译标签？

你在设置里打开了翻译标签吗

**Comment by yinzhefuyun** [comment]
> > 1.7.15无法翻译标签，能否自行导入翻译标签？
> 
> 你在设置里打开了翻译标签吗

早就打开了，打开的瞬间会有大概的300KB的流量产生，可是标签并没有被翻译

**Comment by NekoInverter** [comment]
> > > 1.7.15无法翻译标签，能否自行导入翻译标签？
> > 
> > 
> > 你在设置里打开了翻译标签吗
> 
> 早就打开了，打开的瞬间会有大概的300KB的流量产生，可是标签并没有被翻译

打开的时候并不会有流量产生，开关和翻译下不下载没关系
发一下日志看看

**Comment by yinzhefuyun** [comment]
> > > > 1.7.15无法翻译标签，能否自行导入翻译标签？
> > > 
> > > 
> > > 你在设置里打开了翻译标签吗
> > 
> > 
> > 早就打开了，打开的瞬间会有大概的300KB的流量产生，可是标签并没有被翻译
> 
> 打开的时候并不会有流量产生，开关和翻译下不下载没关系
> 发一下日志看看

没事了，我今天早上忘记退出软件如何在手机上app挂了一天，回家的时候中文出现了

**Comment by lulu213** [comment]
>

**Comment by lulu213** [comment]
记:https://pan.baidu.com/s/1qflEZqIC9H0JGccdUba4ZQ 提取码:62f9
日记 没有翻译

**Comment by lulu213** [comment]
好了，挂梯子都没见下载好，下午一打开就有了

**Comment by MichaelMai2000** [comment]
人在墙外，开关已开，标签数据似乎仍未加载/也没有观察到在下载。
我再观察一下，之后有必要就贴个日志。

**Comment by NekoInverter** [comment]
https://cdn.jsdelivr.net/gh/NekoInverter/tag-translations@main/tag-translations-v2/tag-translations-zh-rCN
这个是下载翻译的链接，可以看看能不能打开

**Comment by yinzhefuyun** [comment]
> https://cdn.jsdelivr.net/gh/NekoInverter/tag-translations@main/tag-translations-v2/tag-translations-zh-rCN
> 这个是下载翻译的链接，可以看看能不能打开

用notepad++打开，改UTF-8后发现，第一行乱码

**Comment by NekoInverter** [comment]
> > https://cdn.jsdelivr.net/gh/NekoInverter/tag-translations@main/tag-translations-v2/tag-translations-zh-rCN
> > 这个是下载翻译的链接，可以看看能不能打开
> 
> 用notepad++打开，改UTF-8后发现，第一行乱码

那是正常的
