### ISSUE TITLE
无法下载种子

### ISSUE THREAD

**Issue by BlueJett** [NekoInverter/EhViewer#2]
**简略描述 / Describe the bug**
在点击下载种子之后无任何反应
**如何重现 / To Reproduce**
任意打开一个带有种子的图集后尝试下载
**预期行为 / Expected behavior**
会直接调用系统下载器开始下载
**截图 / Screenshots**
/
**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：SM-T350
 - Android 版本：crDroid v5.11

**备注 / Additional context**
在未提交commit的1.7.4原版使用正常

**Comment by NekoInverter** [comment]
应该修好了吧

**Comment by BlueJett** [comment]
已修复，谢谢
