### ISSUE TITLE
1.7.9 右侧快速搜索 上下滑动会变成调整标签顺序

### ISSUE THREAD

**Issue by k7kkl** [NekoInverter/EhViewer#21]
**简略描述 / Describe the bug**
大概说下是什么问题。

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题

**预期行为 / Expected behavior**
应该是什么样子的？

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】
 - Android 版本：【比如 Android 12.1】
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]

**备注 / Additional context**
还有什么想说的？

**Comment by NekoInverter** [comment]
Fixed in 1.7.10
