### ISSUE TITLE
1.7.10纯黑深色主题下侧边栏是深色不是纯黑的

### ISSUE THREAD

**Issue by bakabaka2333** [NekoInverter/EhViewer#25]
![Screenshot_20201019-231155_看图王](https://user-images.githubusercontent.com/45543164/96463113-527d4080-1261-11eb-9716-4d9a03a2d5de.png)

安卓7.0平板

**Comment by NekoInverter** [comment]
完全都是黑的话..就没层次感了（
纯黑本来就是烂烂设计

**Comment by bakabaka2333** [comment]
emmmm.....搞个设置选项也行啊

**Comment by bakabaka2333** [comment]
算了吧= =...也不影响使用

**Comment by NekoInverter** [comment]
[release.zip](https://github.com/NekoInverter/EhViewer/files/5406090/release.zip)
看看这个（

**Comment by bakabaka2333** [comment]
好了 谢谢dalao
