### ISSUE TITLE
[bug] 非 Cookies 方式登入时，无法访问 Ex里画廊

### ISSUE THREAD

**Issue by gth7754125** [NekoInverter/EhViewer#26]
### Description:
> EhViewer：1.7.11版本
> 初次安装使用。

### Bug
> 使用`网页登录` `或者`直接客户端登录时`，能登录使用Ehentai，但切换成 ex 画廊后无法获取信息。
> 可能是 Cookies 内的 igneous默认成了 mystery ？
> 换用 Cookies 手动登录可以进入.

**Comment by NekoInverter** [comment]
这我也没办法

**Comment by gth7754125** [comment]
额，其实我不太清楚原因。但是一般表站能登录但里站登不进去应该就是cookies的问题。换到客户端上是前端那里负责控制cookies的，所以估计是那里设置有问题才导致另外的登录方式没法应用到里站画廊。

**Comment by NekoInverter** [comment]
eh 没给 igneous 我也没办法
