### ISSUE TITLE
搜索列表添加显示被收藏数量的数字

### ISSUE THREAD

**Issue by wordly123** [NekoInverter/EhViewer#27]
这个功能其实非常好，能一眼就在查询列表看见最受欢迎的本子，（e站评分不大行）早在2018年的时候有人就提交了这个功能申请，但是原作者一直没有做，我怀疑是因为e站本身搜索列表就根本查不出来这个字段，因为e站已经有反爬技术我找不到任何关于显示的信息，然后我看了下源码，其中GalleryInfo这类中我找不到任何关于被收藏数量有关的字段，而在GalleryDetail这个类中我发现了favoriteCount这个字段，就这么说吧如果搜索列表中能查到这个被收藏的数量的字段就可以直接拿出来展示，当然如果没有的话，这里实现确实很麻烦，如果一次查询查25个画廊的话，就需要拿到这些画廊的gid再去查详情，（这里不知道查画廊详情需要哪些参数）然后在返回的参数对应展示到每一个画廊上。说实话这样查询一次原本只需要发一个请求的，结果发了26个请求emmmmmm，感觉我这个想法不靠谱，希望能完成这个功能吧。

**Comment by NekoInverter** [comment]
搜索列表确实没给收藏数...
一个一个查那效率太低了还很可能被 ban

**Comment by wordly123** [comment]
> 搜索列表确实没给收藏者数量...
> 一个一个查那效率太低了还很可能被禁

那这个·功能只能等官方提供了，而且有了这个玩意就会有按照收藏数量排序，但是我觉得这么多年了e站这边应该是故意不做这个功能的，毕竟每个人喜好不同。。。。。。  但是按照评分搜索为啥一直都有
