### ISSUE TITLE
主页左右滑动问题

### ISSUE THREAD

**Issue by lastice** [NekoInverter/EhViewer#3]
1.7.3的官方版本，在主页任意位置左右滑动都可以呼出侧边栏
但是大佬修改后的1.7.4就不行了，只有屏幕边缘滑动才行，但这又和全面屏手势冲突了，不如以前的方便，希望大佬可以修改一下

**Comment by NekoInverter** [comment]
> 1.7.3的官方版本，在主页任意位置左右滑动都可以呼出侧边栏
> 但是大佬修改后的1.7.4就不行了，只有屏幕边缘滑动才行，但这又和全面屏手势冲突了，不如以前的方便，希望大佬可以修改一下

本来就是这样

**Comment by duzhaokun123** [comment]
抬个扛，tg android 客户端可以在中间滑动打开抽屉

**Comment by NekoInverter** [comment]
> 抬个扛，tg android 客户端可以在中间滑动打开抽屉

那是 TAndroid 自己写的抽屉（
如果对我这个抽屉有问题可以去找 Google

**Comment by NekoInverter** [comment]
抽屉在原生 Android 10 + 手势导航下是完全没有任何问题可以滑出的，滑不出来请给你的系统维护者反馈 Bug

**Comment by NekoInverter** [comment]
https://github.com/NekoInverter/EhViewer/commit/e74e7b4a9d40ced92e36f319cf8617bfd9f6d983
加入了替代滑动的打开方式

**Comment by NekoInverter** [comment]
在下个版本应该可以解决
