### ISSUE TITLE
可以换一个包名吗

### ISSUE THREAD

**Issue by ts8zs** [NekoInverter/EhViewer#30]
希望能和老版本共存

**Comment by youshaojie** [comment]
我也希望能和旧版共存

**Comment by ssbroad** [comment]
同样希望可以共存

**Comment by ZerOri** [comment]
h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了

**Comment by ts8zs** [comment]
> h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了

并没有。。。有一说一，这件事大家懂得都懂，不懂得，说了你也不明白，不如不说。你们也别来问我怎么了，利益牵扯太大，说了对你们也没什么好处，当不知道就行了，其余的我只能说这里面水很深，牵扯到很多大人物。详细资料你们自己找是很难找的，网上大部分已经删除干净了，所以我只能说懂得都懂，不懂得也没办法。

**Comment by NekoInverter** [comment]
改了✔

**Comment by ZerOri** [comment]
> > h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了
> 
> 并没有停止维护。。。有一说一，这件事大家懂得都懂，不懂得，说了你也不明白，不如不说。你们也别来问我怎么了，利益牵扯太大，说了对你们也没什么好处，当不知道就行了，其余的我只能说这里面水很深，牵扯到很多大人物。详细资料你们自己找是很难找的，网上大部分已经删除干净了，所以我只能说懂得都懂，不懂得也没办法。

那在哪里更新？？？

**Comment by ts8zs** [comment]
> > > h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了
> > 
> > 
> > 并没有停止维护。。。有一说一，这件事大家懂得都懂，不懂得，说了你也不明白，不如不说。你们也别来问我怎么了，利益牵扯太大，说了对你们也没什么好处，当不知道就行了，其余的我只能说这里面水很深，牵扯到很多大人物。详细资料你们自己找是很难找的，网上大部分已经删除干净了，所以我只能说懂得都懂，不懂得也没办法。
> 
> 那在哪里更新？？？

tg

**Comment by ZerOri** [comment]
> > > > h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了
> > > 
> > > 
> > > 并没有停止维护。。。有一说一，这件事大家懂得都懂，不懂得，说了你也不明白，不如不说。你们也别来问我怎么了，利益牵扯太大，说了对你们也没什么好处，当不知道就行了，其余的我只能说这里面水很深，牵扯到很多大人物。详细资料你们自己找是很难找的，网上大部分已经删除干净了，所以我只能说懂得都懂，不懂得也没办法。
> > 
> > 
> > 那在哪里更新？？？
> 
> tg

怎么突然又更新了 笑cry

**Comment by ts8zs** [comment]
tg




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zero O"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 中午11:45
收件人: "NekoInverter/EhViewer"<EhViewer@noreply.github.com&gt;; 
抄送: "ts8zs"<ts8zs@ts8zs.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NekoInverter/EhViewer] 可以换一个包名吗 (#30)





   
h大原版停止维护了，长痛不如短痛还是尽早迁移吧，我倒是希望能获得h大授权签名，可以覆盖安装就好了
  
并没有停止维护。。。有一说一，这件事大家懂得都懂，不懂得，说了你也不明白，不如不说。你们也别来问我怎么了，利益牵扯太大，说了对你们也没什么好处，当不知道就行了，其余的我只能说这里面水很深，牵扯到很多大人物。详细资料你们自己找是很难找的，网上大部分已经删除干净了，所以我只能说懂得都懂，不懂得也没办法。
  
那在哪里更新？？？
 
&mdash;
