### ISSUE TITLE
[Feature Request] F-Droid Release and Remove Trackers

### ISSUE THREAD

**Issue by grravity** [NekoInverter/EhViewer#33]
**Requesting that you add EHViewer onto F-Droid.**
It would be very nice.   
https://f-droid.org/ 
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/ 

**I am also highly suggesting to remove the trackers.** 

Microsoft Visual Studio App Center Analytics
Microsoft Visual Studio App Center Crashes

*Microsoft Visual Studio App Center Analytics
6com.microsoft.appcenter.analytics

*Microsoft Visual Studio App Center Crashes
9com.microsoft.appcenter.crashes

**Comment by NekoInverter** [comment]
AppCenter is not enabled by default, and F-Droid is stupid.
