### ISSUE TITLE
Tag realporn和Tag bondage似乎有冲突？

### ISSUE THREAD

**Issue by lithium148** [NekoInverter/EhViewer#36]
搜索框中输入“FEMALE:BONDAGE misc:realporn”，无法显示任何结果；输入“bondage realporn”也一样。

我确定这个Tag组合能搜索到结果，因为我在其他家的eh阅读器能搜索到。

exhentai，其他内容都能搜到，唯独这两个tag一起搜不行。

麻烦开发者大大看下是不是我的使用放大不对，谢谢！

**Comment by NekoInverter** [comment]
网页也搜不到

**Comment by sdshdv** [comment]
realporn在E站属于禁止标签，有这个标签的画廊都将面临被删除和隐藏的结果，并不是什么好tag，具体解释详见：https://ehwiki.org/wiki/Expunging#Realporn
如果你一定要看，需要先打开高级选项里的“显示被删除的画廊”然后就能搜索到了

**Comment by lithium148** [comment]
> realporn在E站属于禁止标签，有这个标签的画廊都将面临被删除和隐藏的结果，并不是什么好tag，具体解释详见：https://ehwiki.org/wiki/Expunging#Realporn
> 如果你一定要看，需要先打开高级选项里的“显示被删除的画廊”然后就能搜索到了

感谢回复，但我在exhentai网站的设置和app的设置都没有看到“显示被删除的画廊”选项，是否意味着我没有权限？

**Comment by NekoInverter** [comment]
> > realporn在E站属于禁止标签，有这个标签的画廊都将面临被删除和隐藏的结果，并不是什么好tag，具体解释详见：https://ehwiki.org/wiki/Expunging#Realporn
> > 如果你一定要看，需要先打开高级选项里的“显示被删除的画廊”然后就能搜索到了
> 
> 感谢回复，但我在exhentai网站的设置和app的设置都没有看到“显示被删除的画廊”选项，是否意味着我没有权限？

![Screenshot_20201102-112603](https://user-images.githubusercontent.com/42698724/97827086-3d42f000-1cfe-11eb-9076-26f6fb4e2a7d.png)
有的

**Comment by lithium148** [comment]
> > > realporn在E站属于禁止标签，有这个标签的画廊都将面临被删除和隐藏的结果，并不是什么好tag，具体解释详见：https://ehwiki.org/wiki/Expunging#Realporn
> > > 如果你一定要看，需要先打开高级选项里的“显示被删除的画廊”然后就能搜索到了
> > 
> > 
> > 感谢回复，但我在exhentai网站的设置和app的设置都没有看到“显示被删除的画廊”选项，是否意味着我没有权限？
> 
> ![Screenshot_20201102-112603](https://user-images.githubusercontent.com/42698724/97827086-3d42f000-1cfe-11eb-9076-26f6fb4e2a7d.png)
> 有的

**谢谢开发者大佬！**
