### ISSUE TITLE
Not able to update app. 

### ISSUE THREAD

**Issue by Omagician** [NekoInverter/EhViewer#37]
**简略描述 / Describe the bug**
大概说下是什么问题。
Trying to update the app to the latest version and I cannot get it to install. Every attempt says that the app was not installed.

**设备型号与 Android 版本 / Device model and Android version**
 
 - Device model: Samsung Galaxy A10e
 - Android version:  10

**备注 / Additional context**
还有什么想说的？
The version of the app I have installed is 1.7.3 I believe it was created by hippo. Wasn't sure if the updates for later versions on here would work I've tried several of them and none of them work

**Comment by zeluqa** [comment]
Why is this closed? I'm currently having the same problem.

**Comment by NekoInverter** [comment]
You need to uninstall old version due to different signature
