### ISSUE TITLE
hello, why i cant see comment from ehviewer lately? theres no problem when checking via web

### ISSUE THREAD

**Issue by nxscythelynz** [NekoInverter/EhViewer#38]
just to tell you, also i think some other user also has this problem
would be nice if you can fix, thanks in advance

**Comment by Omagician** [comment]
Yeah  I am having the same problem. I tried updating and cant install anything.

**Comment by LawdStalker** [comment]
If you're using 1.7.3, instead of updating, uninstall it and install the last release from this repository (1.7.12).
Don't forget to export you data before that
