### ISSUE TITLE
下载内容超过250G之后出现问题

### ISSUE THREAD

**Issue by JKKKK5214** [NekoInverter/EhViewer#44]
把旧SD卡中的下载内容移到新TF卡中，一开始能正常下载。但后面TF卡的使用达到了250G左右后，无论下载什么作品都直接失败，除非删掉一些作品，这样又可以恢复正常继续下载。具体症状为选择下载，卡顿一下直接下载失败，继续点击下载瞬间显示下载失败。而手机上显示TF卡上还有270G的内存可以使用。
手机为全新的红米 note 8 pro
TF卡为雷克斯的512G卡

**Comment by NekoInverter** [comment]
假卡吧

**Comment by gongter** [comment]
我也是红米NOTE8P 如果外置存储就一直下载失败未知主机，但一直反复下文件

**Comment by mo-han** [comment]
瞬间下载失败，但是可以在线浏览，大概率是文件写入失败，这是我的个人经验
（那次我发现怎么点都是下载失败，找了半天原因，最后发现TF卡已经满了，🤣
