### ISSUE TITLE
Right swipe not registering to open menu

### ISSUE THREAD

**Issue by Omagician** [NekoInverter/EhViewer#48]
The problem I've noticed since I've update to the newer version is that when you try to swipe from the left to the right to open the menu I have to go to the very edge of my phones screen to open it. It's like it's not reading my swipes and I have to do it many times before it opens. In the past you didn't have to go so far I could just swipe right and the menu would open. 

Is there a way to change the touch zone so it's not so hard to open the menu will browsing.

**Comment by NekoInverter** [comment]
This is intended behavior
