### ISSUE TITLE
从1.7.14导入数据至1.7.15后，1.7.15无法直接查看已经下载的图片

### ISSUE THREAD

**Issue by lbrony** [NekoInverter/EhViewer#49]
**简略描述 / Describe the bug**
从1.7.14导入数据至1.7.15后，1.7.15无法直接查看已经下载的图片

**如何重现 / To Reproduce**
重现的步骤：
准备一个含有已下载的画廊的老版本ehviewer并导出数据，在新版本导入数据，能显示导入成功，且下载页面中可以正常看到与老版本相同的已下载的目录，但是无法在断网状态下查看已下载的画廊，需要重新走一次下载流程（但并不会重复下载）

**预期行为 / Expected behavior**
导入数据之后应与老版本一样，可以直接查看已下载的画廊

**截图 / Screenshots**
![Screenshot_20201117_012631_io github nekoinverter ehviewer](https://user-images.githubusercontent.com/74559397/99286764-4abab700-2874-11eb-896b-2bb0fe22250e.jpg)
![Screenshot_20201117_012636_com hippo ehviewer](https://user-images.githubusercontent.com/74559397/99286771-4ee6d480-2874-11eb-8471-71cbc16094dd.jpg)
可以正常显示内容的图片为老版本，error的为新版本，均在断网状态下截图，截图画廊为同一个已下载的画廊

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：Honor 30s
 - Android 版本：10（magic ui 3.1.1)

**备注 / Additional context**
从绿色图标的ehviewer转移到黄色图标的ehviewer时就有此问题，重新跑一次下载还是不太方便，尤其是有仓鼠癌的话

**Comment by NekoInverter** [comment]
发日志

**Comment by lbrony** [comment]
我是为了报告这个“问题”注册的GitHub，不太熟悉GitHub的使用，在issue中也没有看到“日志”，因此不知道如何“发日志”，造成麻烦非常抱歉

**Comment by lbrony** [comment]
> 发日志

已补从1.7.15的“高级-导出日志”中导出的文件
