### ISSUE TITLE
Andriond 10 下载中无法右侧边缘滑动,呼出下载分类

### ISSUE THREAD

**Issue by kk9448** [NekoInverter/EhViewer#5]
**简略描述 / Describe the bug**
大概说下是什么问题。

由于one ui在andriod 10中,默任屏幕边缘滑动是返回, 会导致先触发返回,无法触发下载分类菜单

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题

**预期行为 / Expected behavior**
应该是什么样子的？

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】
 - Android 版本：【比如 Android 12.1】
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]

**备注 / Additional context**
还有什么想说的？

**Comment by NekoInverter** [comment]
Google 要求的正确的触发手势是稍稍停留再滑动，如果不行那是三星的问题（

**Comment by NekoInverter** [comment]
而且 Google 没给 API 改触发范围🌚
