### ISSUE TITLE
能否优先显示已搜索过的词条而并非联想词条

### ISSUE THREAD

**Issue by S1monGao** [NekoInverter/EhViewer#56]
**这个功能是用来解决问题的吗？ / Is your feature request related to a problem? Please describe.**
在搜索栏输入关键字后在下拉菜单中，相关的已搜索过的词条显示在联想词条之后

**描述你想要的解决方法 / Describe the solution you'd like**
优先显示已搜索过的词条

**Comment by NekoInverter** [comment]
3209cdefb3d06a106f37e296d5f38f4aa037ac06
