### ISSUE TITLE
下拉选择有问题

### ISSUE THREAD

**Issue by Dr-cdfg** [NekoInverter/EhViewer#57]
**简略描述**
设置里下拉菜单显示异常，详细看截图。

**如何重现**
重现的步骤：
1. 打开设置
2. 点击任意一个下拉菜单

**预期行为**
![截屏_20201122_201450](https://user-images.githubusercontent.com/55901382/99903717-078f9680-2d01-11eb-85db-533723c245c4.jpg)

**截图**
![截屏_20201122_201431](https://user-images.githubusercontent.com/55901382/99903721-124a2b80-2d01-11eb-91a2-2bf5e3dd383f.jpg)

**设备型号与 Android 版本**
 - 设备型号：Vivo Y55A
 - Android 版本：Android 6.0.1（FuntouchOS 2.6）

**备注**
我的另一台Vivo x9也有此问题（Android 8）

**Comment by NekoInverter** [comment]
VIVO 的问题
