### ISSUE TITLE
阅读漫画时提示：获取pToken错误

### ISSUE THREAD

**Issue by NigelSong** [NekoInverter/EhViewer#59]
**简略描述 / Describe the bug**
大概说下是什么问题。
观看漫画时加载失败，提示“获取pToken错误”

**如何重现 / To Reproduce**
重现的步骤：
1. 打开什么什么
2. 点击什么什么
3. 出现什么什么问题
登录账号，e-hentai源，点击任意一个画廊，点击任意一张缩略图进入阅读模式后，出现问题。

**预期行为 / Expected behavior**
应该是什么样子的？
正常加载并显示漫画内容

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。
![Screenshot_20201125-171218](https://user-images.githubusercontent.com/23294384/100206873-dc47ba00-2f41-11eb-97ef-5aa65b8a23ec.jpg)

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：【比如 Pixel 6 XXXL】
 - Android 版本：【比如 Android 12.1】
 - Device model: [e.g. Pixel 6 XXXL]
 - Android version: [e.g. Android 12.1]
型号：一加6 ONEPLUS A6000 
系统版本：氢OS Android 10

**备注 / Additional context**
还有什么想说的？
试过重新登录与更换梯子节点，都没有效果；使用网页版浏览漫画正常，软件版本1.7.15，期待开发大大的回复

**Comment by NekoInverter** [comment]
可能是网络问题

**Comment by NekoInverter** [comment]
如果是直连的话建议开一下 DoH

**Comment by NigelSong** [comment]
破案了，把Multi-Page Viewer选项关了就能看了。感谢开发大大的回复！
