### ISSUE TITLE
没办法切换收藏夹了

### ISSUE THREAD

**Issue by Trendymen** [NekoInverter/EhViewer#6]
**简略描述 / Describe the bug**
大概说下是什么问题。
收藏夹我第一次点了云端收藏 之后 收藏界面右划没有出现切换收藏夹的右菜单栏
**如何重现 / To Reproduce**
重现的步骤：
1. 收藏夹界面
2. 右划

**预期行为 / Expected behavior**
应该是什么样子的？

能够弹出切换收藏夹切换菜单

**截图 / Screenshots**
能截图的话就发截图，请注意风序良俗。

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：三星s10
 - Android 版本： Android10

**备注 / Additional context**
还有什么想说的？

nothing,thanks.

**Comment by NekoInverter** [comment]
我这没问题..

**Comment by Trendymen** [comment]
> 我这没问题..
> 以及应该左滑...
> Edit: 你应该在屏幕边缘滑

左滑右滑都失效了... 以前在屏幕左边右滑 还能出菜单的..是手机问题么 之前作者原版没问题... 
顺便，感谢维护

**Comment by NekoInverter** [comment]
你试试手指在屏幕边缘停留一下再划？

**Comment by Trendymen** [comment]
> 你试试手指在屏幕边缘停留一下再划？

不行哦

**Comment by NekoInverter** [comment]
那可能是三星的系统问题（

**Comment by Trendymen** [comment]
> 那可能是三星的系统问题（

好的 这就买新手机去😈 
开玩笑的 这年头的小米都买不起了
