### ISSUE TITLE
app无法检查更新？

### ISSUE THREAD

**Issue by zx900930** [NekoInverter/EhViewer#60]
既然改了包名，是不是可以把检测版本更新也加上，
现在那个更新按钮好像是无效的。
![Screenshot_2020-11-26-11-10-09-640_io github nekoinverter ehviewer](https://user-images.githubusercontent.com/734749/100337684-00ee7100-2fd8-11eb-8de8-49f51b721b23.jpg)

**Comment by NekoInverter** [comment]
这个点了是没提示...不过是有用的

**Comment by zx900930** [comment]
> 这个点了是没提示...不过是有用的

我刚刚1.7.15点了很多下检测更新都没反应，而且不止一次，是不是还有哪个选项需要打开才能检测更新？
