### ISSUE TITLE
预览图清晰度太低

### ISSUE THREAD

**Issue by sdshdv** [NekoInverter/EhViewer#63]
**这个是原版本app预览图：**
![Screenshot_20201127-112653__01](https://user-images.githubusercontent.com/28926503/100407673-02856b00-30a4-11eb-8de9-a5651a3bd662.jpg)
**这个是当前版本的app预览图：**
![Screenshot_20201127-112715__01](https://user-images.githubusercontent.com/28926503/100407709-16c96800-30a4-11eb-869a-f8dedef45294.jpg)
可以明显看到预览图清晰度差别明显，虽然影响不大，但是还是希望可以改成和原版一样的清晰度

**Comment by NekoInverter** [comment]
缩略图清晰度和我有什么关系？

**Comment by NekoInverter** [comment]
试了一下，似乎里站就这个清晰度...

**Comment by NekoInverter** [comment]
![image](https://user-images.githubusercontent.com/42698724/100412399-8e50c480-30af-11eb-92b9-79830b8bdbf6.png)
用与 App 一样的 Cookies 去网页版点一下这个就好了...

**Comment by NekoInverter** [comment]
![image](https://user-images.githubusercontent.com/42698724/100412503-df60b880-30af-11eb-8358-928349c0699e.png)
或者在 EHentail 设置里改一下这个
