### ISSUE TITLE
无法下载压缩包

### ISSUE THREAD

**Issue by ygsk10** [NekoInverter/EhViewer#7]
**简略描述 / Describe the bug**
大概说下是什么问题。

**如何重现 / To Reproduce**
重现的步骤：
1. 配置H@H客户端
2. 登录
3. 随便找个画廊下载压缩包
4. 什么都不会发生

**预期行为 / Expected behavior**
应该是什么样子的？
通知栏出现下载进度

**Comment by NekoInverter** [comment]
这个下载压缩包不是下载到本地吧？

**Comment by ygsk10** [comment]
> 这个下载压缩包不是下载到本地吧？

我看到eh网页是可以获取下载链接下载到本地的
![Screenshot_20200801-184629](https://user-images.githubusercontent.com/60314251/89100142-6023e680-d427-11ea-9a8e-7698c9b5c320.png)

**Comment by ygsk10** [comment]
在 H@H 服务器 ~/download 看到了
这个设计有点蠢
